# Generated by Django 4.2.11 on 2024-03-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_yourmodel_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
