# Generated by Django 4.2.11 on 2024-03-18 15:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
