# Generated by Django 4.2.11 on 2024-03-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
